required: sudo
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
before_install:
  - sudo -u postgres createdb loopback
  - sudo -u postgres createuser -s loopback
  - sudo adduser loopback --disabled-password --gecos --no-create-home
  - echo -e "loopback\nloopback\n" | sudo passwd loopback
install:
  - npm install
test:
 - npm test
post-test:
  - tar loopback.tar *
